[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
from = "/404"
to = "/404.html"
status = 404

# Redirections depuis l’ancien slug
[[redirects]]
from = "/redaction"
to = "/textes"
status = 301
force = true

[[redirects]]
from = "/redaction.html"
to = "/textes.html"
status = 301
force = true

# Sécurité
[[headers]]
for = "/*"
  [headers.values]
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"
  Content-Security-Policy = "default-src 'self' https: data: blob:; img-src 'self' https: data: blob:; script-src 'self' https: 'unsafe-inline' 'unsafe-eval'; style-src 'self' https: 'unsafe-inline'; font-src 'self' https: data:; connect-src 'self' https:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"

# Cache long
[[headers]]
for = "/**/*.{css,js,woff,woff2,png,jpg,jpeg,svg,webp,gif}"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
