[build]
  command = "npm run build"
  publish = "_site"

# Conserver ces URL propres
[[redirects]]
  from = "/merci"
  to = "/merci.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
  force = true

# IMPORTANT : aucune réécriture sur /admin/* pour laisser charger config.yml
