# netlify.toml — cache agressif + préchargements
[build]
  publish = "_site"
  command = "npm run build"

# Compression est auto sur Netlify. On renforce le cache.

# Cache fort pour images optimisées
[[headers]]
  for = "/optimized-img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fort pour uploads bruts si référencés
[[headers]]
  for = "/static/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache statique pour CSS
[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Link = "</styles.css>; rel=preload; as=style"

# Préchargement police si vous en ajoutez (exemple, à adapter)
# [[headers]]
#   for = "/static/fonts/*.woff2"
#   [headers.values]
#     Cache-Control = "public, max-age=31536000, immutable"
#     Link = "</static/fonts/myfont.woff2>; rel=preload; as=font; type=font/woff2; crossorigin"

# Sécurité basique
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
