[build]
  command = "npm run build"
  publish = "_site"

# URLs propres
[[redirects]]
  from = "/merci"
  to = "/merci.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
  force = true

# Dashboard CMS — pas de wildcard pour ne pas toucher config.yml
[[redirects]]
  from = "/dashboard"
  to = "/dashboard/index.html"
  status = 200
  force = true

# CSP site
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = '''
    default-src 'self' https:;
    script-src  'self' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/;
    frame-src   'self' https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/;
    style-src   'self' 'unsafe-inline' https:;
    img-src     'self' data: https:;
    font-src    'self' data: https:;
    connect-src 'self' https:;
  '''

# CSP assouplie pour le CMS
[[headers]]
  for = "/dashboard/*"
  [headers.values]
  Content-Security-Policy = '''
    default-src 'self' https:;
    script-src  'self' 'unsafe-eval' https://unpkg.com https://cdn.jsdelivr.net https://identity.netlify.com;
    frame-src   'self' https://identity.netlify.com;
    style-src   'self' 'unsafe-inline' https:;
    img-src     'self' data: https:;
    font-src    'self' data: https:;
    connect-src 'self' https:;
  '''
