[build]
  command = "npm run build"
  publish = "_site"

# URLs propres existantes
[[redirects]]
  from = "/merci"
  to = "/merci.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
  force = true

# SPA /dashboard : servir l'app même si l'URL commence par /dashboard
[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

# Sécurité + reCAPTCHA
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = '''
    default-src 'self' https:;
    script-src  'self' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/;
    frame-src   'self' https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/;
    style-src   'self' 'unsafe-inline' https:;
    img-src     'self' data: https:;
    font-src    'self' data: https:;
    connect-src 'self' https:;
  '''
