[build]
  command = "npm run build"
  publish = "_site"

# URLs propres existantes
[[redirects]]
  from = "/merci"
  to = "/merci.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
  force = true

# SPA dashboard et CMS (hash router)
[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200

# CSP par défaut du site
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = '''
    default-src 'self' https:;
    script-src  'self' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/;
    frame-src   'self' https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/;
    style-src   'self' 'unsafe-inline' https:;
    img-src     'self' data: https:;
    font-src    'self' data: https:;
    connect-src 'self' https:;
  '''

# Assouplissement uniquement pour le dashboard/CMS
[[headers]]
  for = "/dashboard/*"
  [headers.values]
  Content-Security-Policy = '''
    default-src 'self' https:;
    # Netlify CMS a besoin de 'unsafe-eval' et des CDN JS
    script-src  'self' 'unsafe-eval' https://unpkg.com https://cdn.jsdelivr.net https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/;
    frame-src   'self' https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/;
    style-src   'self' 'unsafe-inline' https:;
    img-src     'self' data: https:;
    font-src    'self' data: https:;
    connect-src 'self' https:;
  '''
