backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow
locale: "fr"

collections:
  - name: "redactions"
    label: "Rédactions"
    folder: "content/redactions"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Texte", name: "body", widget: "markdown" }
